Feat: workspaceId and projectID support for wf submit
zapatacomputing/orquestra-workflow-sdk pull request #109
Opened 2023-04-06 12:00 UTC by SebastianMorawiec

# The problem

_Please describe the motivation for this PR. Bonus points for code examples, error messages, and screenshots._

# This PR's solution

_Please describe the PR's content. Bonus points for code examples, error messages, screenshots._

# Checklist

_Check that this PR satisfies the following items:_

- [ ] Tests have been added for new features/changed behavior (if no new features have been added, check the box).
- [ ] The [changelog file](CHANGELOG.md) has been updated with a user-readable description of the changes (if the change isn't visible to the user in any way, check the box).
- [ ] The PR's title is prefixed with `<feat/fix/chore/internal/docs>[!]:`

2023-04-06 13:36 UTC, alexjuda commented on src/orquestra/sdk/_base/_in_process_runtime.py
> +        project_id: t.Optional[str] = None,
It would be nice to have a type alias like `WorkspaceID` and `ProjectID`, especially given the fact we might have human friendly strings soon too.

2023-04-06 13:37 UTC, alexjuda commented on src/orquestra/sdk/exceptions.py
> +    pass
```suggestion
class UnsupportedFeature(Warning):
    pass
```
?

2023-04-11 10:07 UTC, alexjuda requested changes
Apart from the `by_id()` thing I've added a few non-blocking thoughts and suggestions :)

2023-04-13 13:15 UTC, SebastianMorawiec commented on src/orquestra/sdk/_base/_qe/_qe_runtime.py
> +                category=exceptions.UnsupportedRuntimeFeature,
only if they provide Project, which they shouldnt if they use QE

2023-04-13 13:29 UTC, alexjuda approved these changes
LGTM but please merge it after https://github.com/zapatacomputing/orquestra-workflow-sdk/pull/114/files

2023-04-13 13:29 UTC, alexjuda commented on src/orquestra/sdk/_base/abc.py
> +                When omitted, WF will be scheduled at default project
**praise**: thanks, that's exactly what I was hoping for!

2023-04-14 11:37 UTC, merged