Feat: Add new config "self" to submit to CE from within a cluster
zapatacomputing/orquestra-workflow-sdk pull request #117
Opened 2023-04-17 11:49 UTC by SebastianMorawiec

# The problem

Clusters have embedded passport token to be used from within their internals.
For user convenience they shouldn't have to log-in into the same cluster from within portal studio

# This PR's solution

add new config named <self> which can be used to interact with CE from within portal and studio.

# Checklist

_Check that this PR satisfies the following items:_

- [ ] Tests have been added for new features/changed behavior (if no new features have been added, check the box).
- [ ] The [changelog file](CHANGELOG.md) has been updated with a user-readable description of the changes (if the change isn't visible to the user in any way, check the box).
- [ ] The PR's title is prefixed with `<feat/fix/chore/internal/docs>[!]:`

2023-04-17 16:40 UTC, alexjuda requested changes

2023-04-18 08:13 UTC, SebastianMorawiec commented on src/orquestra/sdk/_base/_config.py
> +SAME_CLUSTER_CONFIG_NAME = "self"
There was a thread on slack: https://zapatista.slack.com/archives/C02V25SBGS3/p1681472324307459?thread_ts=1681466373.464069&cid=C02V25SBGS3 where we discussed it.
We can get back to it anyway if you want offline

2023-04-18 14:05 UTC, alexjuda commented
Related to: https://zapatacomputing.atlassian.net/browse/ORQSDK-772

2023-04-18 14:11 UTC, alexjuda approved these changes
LGTM, with some non-blocking suggestions :)

2023-04-18 14:11 UTC, alexjuda commented on src/orquestra/sdk/_base/_config.py
> +SAME_CLUSTER_CONFIG_NAME = "self"
Extracted into:
* https://zapatacomputing.atlassian.net/browse/ORQSDK-818
* https://zapatacomputing.atlassian.net/browse/ORQSDK-819

2023-04-18 14:13 UTC, merged