Feat: New API functions: list_workspaces and list_projects
zapatacomputing/orquestra-workflow-sdk pull request #139
Opened 2023-04-28 09:51 UTC by SebastianMorawiec

# The problem

User could not list workspaces and projects lists

# This PR's solution

Create new API functions that return all workspaces and projects 

# Checklist

_Check that this PR satisfies the following items:_

- [ ] Tests have been added for new features/changed behavior (if no new features have been added, check the box).
- [ ] The [changelog file](CHANGELOG.md) has been updated with a user-readable description of the changes (if the change isn't visible to the user in any way, check the box).
- [ ] The PR's title is prefixed with `<feat/fix/chore/internal/docs>[!]:`
- [ ] The PR is linked to a JIRA ticket (if there's no suitable ticket, check the box).

2023-04-28 12:32 UTC, BenjaminMummery requested changes
I have a couple of non-functional suggestions but otherwise LGTM. :) How would you feel about  adding a tutorial for the new features?

2023-04-28 12:32 UTC, BenjaminMummery commented on src/orquestra/sdk/_base/_api/_wf_run.py
> +    return runtime.list_projects(workspace_id_resolved)
Non-blocking suggestion: How would you feel about `resolved_workspace_id` for consistency with `resolved_config`?

```suggestion
    resolved_workspace_id: str

    resolved_workspace_id = (
        workspace_id.workspace_id
        if isinstance(workspace_id, WorkspaceDef)
        else workspace_id
    )

    runtime = resolved_config._get_runtime()

    return runtime.list_projects(resolved_workspace_id)
```

2023-04-28 12:32 UTC, BenjaminMummery commented on src/orquestra/sdk/_base/_driver/_ce_runtime.py
> +                "Could not workspace list "
```suggestion
                "Could not list workspaces "
```

2023-04-28 12:32 UTC, BenjaminMummery commented on src/orquestra/sdk/_base/_driver/_client.py
> +        # we have to build project ZRI from some hardcoded values + workspaceId
Query: is there a documented spec this is based on that we could link to here?

2023-04-28 12:32 UTC, alexjuda requested changes

2023-04-28 12:32 UTC, alexjuda commented on src/orquestra/sdk/schema/workflow_run.py
> +class WorkspaceDef(BaseModel):
As previously discussed in https://github.com/zapatacomputing/orquestra-workflow-sdk/pull/109 `WorkspaceDef` and `ProjectDef` might not be the best names for these records. Usually we keep long-term support for types in `orquestra.sdk.schema` so after we make our mind it's gonna be set in stone. Let's catch up to figure out alternative naming together.

2023-05-02 12:46 UTC, alexjuda approved these changes
LGTM! Added nitpick about copyright notice

2023-05-02 12:46 UTC, alexjuda commented on src/orquestra/sdk/_base/_spaces/_api.py
> +import typing as t
**nitpick**: please add copyright header

2023-05-02 12:46 UTC, alexjuda commented on src/orquestra/sdk/_base/_spaces/_structs.py
> +from dataclasses import dataclass
**nitpick**: please add copyright header

2023-05-02 14:31 UTC, BenjaminMummery approved these changes

2023-05-02 15:58 UTC, merged