!Feat: Dorq task logs command. get_logs() function accepts task invocation ID instead of task run ID
zapatacomputing/orquestra-workflow-sdk pull request #24
Opened 2023-01-19 14:06 UTC by SebastianMorawiec

# The problem

User needs to have CLI command to get logs for individual task

# This PR's solution

Create dorq task logs command.
Also refactor API function get_logs as it was inconsistent with other commands

# Checklist

_Check that this PR satisfies the following items:_

- [x] Tests have been added for new features/changed behavior (if no new features have been added, check the box).
- [x] The [changelog file](CHANGELOG.md) has been updated with a user-readable description of the changes (if the change isn't visible to the user in any way, check the box).
- [x] The PR's title is prefixed with `<feat/fix/chore/internal/docs>[!]:`

2023-01-19 18:11 UTC, alexjuda requested changes

2023-01-19 18:11 UTC, alexjuda commented on src/orquestra/sdk/_base/_api.py
> +        tasks: t.Union[TaskInvocationId, t.List[TaskInvocationId]],
**non-blocking, thought**: Hot take: `tasks` and `only_available` arguments in the `sdk.WorkflowRun` methods have very little value now that we have `sdk.WorkflowRun.get_tasks()`. I'd simply get rid of them.

2023-01-19 18:13 UTC, alexjuda commented on src/orquestra/sdk/_base/_api.py
> +        tasks: t.Union[TaskInvocationId, t.List[TaskInvocationId]],
FYI: I've done just that for `.get_artifacts()` in https://github.com/zapatacomputing/orquestra-workflow-sdk/pull/23

2023-01-20 09:28 UTC, SebastianMorawiec commented on tests/sdk/v2/test_api.py
> +            "task_run3": ["hello\n", "a log\n"],
Ah yes, Ive looped around that what should be here and eventually got the wrong thing :D

2023-01-20 17:15 UTC, alexjuda approved these changes

2023-01-20 17:15 UTC, alexjuda commented on tests/cli/dorq/test_repos.py
> +            def test_passing_values(monkeypatch, mock_by_id, mock_wf_run):
```suggestion
            def test_passing_values(mock_by_id, mock_wf_run):
```

2023-01-20 17:15 UTC, alexjuda commented on tests/cli/dorq/test_repos.py
> +            def test_passing_errors(monkeypatch, mock_by_id, mock_wf_run, exc):
```suggestion
            def test_passing_errors(mock_by_id, mock_wf_run, exc):
```

2023-01-20 17:15 UTC, alexjuda commented on tests/cli/dorq/test_repos.py
> +            def test_wf_not_found(monkeypatch, mock_by_id, exc):
```suggestion
            def test_wf_not_found(mock_by_id, exc):
```

2023-01-23 10:52 UTC, merged