feat: add cli command to generate graphiz graph of a workflow
zapatacomputing/orquestra-workflow-sdk pull request #404
Opened 2024-05-13 11:13 UTC by BenjaminMummery

# The problem

_Please describe the motivation for this PR. Bonus points for code examples, error messages, and screenshots._

# This PR's solution

Adds the following CLI command:

```bash
orq wf graph 
```

There are two potential use cases - either we want to display the graph for a local workflow definition, or we want to display it for a previously submitted workflow. These are handled in the following ways:

## Case 1: Local workflow definition

The only argument we need is the MODULE, which can be supplied via:

```bash
orq wf graph -m MODULE
```

or simply

```bash
orq wf graph MODULE
```

## Case 2: Previously submitted workflow

Any combination of the workflow run id, config, and workspace can be specified. The CLI will prompt the user to select the missing information in the same way as `orq wf status`.

```bash
orq wf graph [-c CONFIG] [-w WORKSPACE] [--id WORKFLOW_RUN_ID]
```

for simplicity we also allow [^1]

```bash
orq wf graph WORKFLOW_RUN_ID [-c CONFIG] [-w WORKSPACE]
```

finally, in parallel with `orq wf status`, the command

```bash
orq wf graph
```

with no arguments prompts the user to select a previously submitted workflow run to display.

# Checklist

_Check that this PR satisfies the following items:_

- [ ] Tests have been added for new features/changed behavior (if no new features have been added, check the box).
- [ ] The [changelog file](CHANGELOG.md) has been updated with a user-readable description of the changes (if the change isn't visible to the user in any way, check the box).
- [ ] The PR's title is prefixed with `<feat/fix/chore/imp[rovement]/int[ernal]/docs>[!]:`
- [ ] The PR is linked to a JIRA ticket (if there's no suitable ticket, check the box).

[ORQSDK-1008]
[^1]: if neither the config nor workspace are provided, we differentiate between `orq wf graph MODULE` and `orq wf graph WF_RUN_ID` by attempting to resolve the argument as a module and first and, if that fails, trying to resolve it as a wf run id.

2024-05-21 09:52 UTC, SebastianMorawiec requested changes

2024-05-21 09:52 UTC, SebastianMorawiec commented on projects/orquestra-sdk/src/orquestra/sdk/_client/_base/cli/_entry.py
> +2) The workflow run ID of a previously submitted workflow.
Suggestion: Having both "workflow" and "id" argument highly complicates stuff where its not really needed. Either leave "workflow" to accept filepath and only that, or remove "id".

2024-05-21 15:12 UTC, BenjaminMummery commented on projects/orquestra-sdk/src/orquestra/sdk/_client/_base/cli/_workflow/_graph.py
> +    def _resolve_remote_workflow_def_graph(self, config, wf_run_id) -> Digraph:
good point, changed "remote" to "submitted" in [84903f4](https://github.com/zapata-engineering/orquestra-sdk/pull/404/commits/84903f4f0e4b5797b15e9077901280d137a1dd1b).

2024-05-29 09:58 UTC, SebastianMorawiec approved these changes
LGTM

2024-05-29 13:05 UTC, merged